{% set name = "stepfunctions" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stepfunctions-{{ version }}.tar.gz
  sha256: 77c668952e2532762e5beb8afe53ab684b9d2964418c4a4b5730c8e40100c3e9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - boto3 >=1.14.38
    - python >=3.6
    - pyyaml
    - sagemaker >=2.1.0

test:
  imports:
    - stepfunctions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/aws-step-functions-data-science-sdk-python
  summary: Open source library for develping data science workflows on AWS Step Functions.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
